"use client";
import React, { useEffect } from 'react'
import HeaderFooter from '../Components/HeaderFooter'
import { useTheme } from 'next-themes';

function Privacy() {
  const {setTheme} = useTheme();
    useEffect(()=>{
        setTheme("light");
      }, []);
  return (
    <>
    <HeaderFooter>
      <div className='bg-[#fbf7f1] py-[5rem]'>
            <div className='text-[2.5rem] text-center font-bold'>Privacy Policy</div>
      </div>

      <div className='flex justify-center'>
        <div className='w-[800px] py-8'>
        <div className='font-semibold'>Effective date: 01.10.2023</div>
           <div className='font-semibold'>Last update date: 27.06.2024</div>

           <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Introduction</div>
            <div>
              <div>Welcome to Foxcolab</div>
              <div>Foxcolab (“us”, “we”, or “our”) operates https://www.Foxcolab.com/ (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to https://www.Foxcolab.com/, and explains how we collect, safeguard, and disclose information that results from your use of our Service.</div>
              <div>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</div>
              <div>Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</div>
            </div>
          </div>

          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Definitions</div>
            <div>
            <b>SERVICE</b> means the https://www.Foxcolab.com/ website operated by Foxcolab. <br />

<b>PERSONAL DATA </b>means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). <br />

<b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit). <br />

Portal Owner are small files stored on your device (computer or mobile device). <br />

<b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data. <br />

<b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively. <br />

<b>DATA SUBJECT </b>is any living individual who is the subject of Personal Data. <br />

<b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data. <br />
            </div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Information Collection and Use</div>
            <div>We collect several different types of information for various purposes to provide and improve our Service to you.</div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Types of Data Collected</div>
            <div>
              <div>
              While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
              <div className='font-semibold'>Full Name</div>
              <div className='font-semibold'>Email</div>
              <div className='font-semibold'>Cookies and Usage Data</div>
              <div>
              We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
              </div>

              </div>
            </div>


            <div>
              <div className='font-semibold'>Usage Data</div>
              <div>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</div>
            </div>

            <div>
            <div className='font-semibold'>Tracking Cookies Data</div>
            <div>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use:</div>
            <div className='font-semibold'>Session Cookies: We use Session Cookies to operate our Service.</div>
            <div className='font-semibold'>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</div>
            <div className='font-semibold'>Security Cookies: We use Security Cookies for security purposes.
</div>
            <div className='font-semibold'>Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
</div>
            


            </div>

            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Use of Data</div>
            <div>Foxcolab uses the collected data for various purposes:</div>
            <div>

            <div>to provide and maintain our Service;</div>
<div>to notify you about changes to our Service;</div>
<div>to allow you to participate in interactive features of our Service when you choose to do so;</div>
<div>to provide customer support;</div>
<div>to gather analysis or valuable information so that we can improve our Service;</div>
<div>to monitor the usage of our Service;</div>
<div>to detect, prevent and address technical issues;</div>
<div>to fulfill any other purpose for which you provide it;</div>
<div>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including forbilling and collection;<div/>
<div>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</div>
<div>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
<div></div>in any other way we may describe when you provide the information; for any other purpose with your consent.
            </div>
            <div>
            </div>
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>6. Retention of Data</div>
            <div> We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
</div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Transfer of Data</div>
            <div>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Foxcolab Platforms Inc.will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
          </div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Disclosure of Data</div>
            <div>We may disclose personal information that we collect, or you provide:</div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>9. Disclosure for Law Enforcement.</div>
            <div>
            If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.

Other cases. We may disclose your information also:
to our subsidiaries and affiliates;
for the purpose of including your company’s logo on our website;
with your consent in any other cases;
if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.
<div className='font-semibold'>Security of Data</div>

The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.


            </div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>10.  Your Data Protection Rights Under General Data Protection Regulation </div>
            <div>
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@Foxcolab.com.
            <div>In certain circumstances, you have the following data protection rights:</div>
            <div>
            the right to access, update or to delete the information we have on you; <br />
the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete; <br />
the right to object. You have the right to object to our processing of your Personal Data;  <br />
the right of restriction. You have the right to request that we restrict the processing of your personal information; <br />
the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format; <br />
the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information; <br />
<div>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</div>
            </div>
            </div>
          </div>

          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Service Providers</div>
            <div>
            We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
            </div>
            <div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Analytics</div>
            <div>We may use third-party Service Providers to monitor and analyze the use of our Service.</div>
            <div className='font-semibold'>Google Analytics</div>
            <div>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.</div>
            <div>
            <div className='font-semibold'>Google Analytics</div>
            <div>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.</div>
              
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Links to Other Sites</div>

            <div>
              Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Children's Privacy</div>
            <div>
            Our Services are not intended for use by children under the age of 18 (“Child” or “Children”). We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Changes to This Privacy Policy</div>
            <div>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.


            </div>
          </div>
          <div className='my-4'>
            <div className='font-semibold text-[1.8rem]'>Contact Us</div>
            <div>
            If you have any questions about this Privacy Policy, please contact us:

By email: support@Foxcolab.com.
            </div>
          </div>
          




          </div>

      </div>
      </div>

    </HeaderFooter>
    
    </>
  )
}

export default Privacy